from typing import Protocol, Iterable


class StorageClient(Protocol):
    def upload_bytes(self, path: str, data: bytes) -> None: ...
    def read_file(self, path: str) -> bytes: ...
    def delete_file(self, path: str) -> None: ...
    def list_files(self, prefix: str) -> Iterable[str]: ...
